Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import time
... 
... # The countdown function is defined below
... 
... def countdown(t):
... 
... while t:
... 
... mins, secs = divmod(t, 60)
... 
... timer = '{:02d}:{:02d}'.format(mins, secs)
... 
... print(timer, end="\r")
... 
... time.sleep(1)
... 
... t -= 1
... 
... print('Lift off!')
... 
... # Ask the user to enter the countdown period in seconds
... 
... t = input("Enter the time in seconds: ")
... 
... # function call
... 
